# Generated by Django 4.1 on 2022-09-14 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], max_length=50)),
                ('status', models.CharField(choices=[('completed', 'COMPLETED'), ('incompleted', 'INCOMPLETED'), ('blocked', 'BLOCKED')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assign_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_from', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to=settings.AUTH_USER_MODEL)),
                ('task_given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_given_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('images', models.FileField(upload_to='media/')),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='workflow.workorder')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
